print("                    CURRICULUM VITAE                    ")
print("DATE PERSONALE")
print("Nume.Prenume: Iacuboi Anna")
print("Adresa: E.Pottier 21")
print("Telefon: 060507682")
print("Locul si data nasterii: mun.Balti, 09.10.2004")
print("STUDII")
print("-9 clase, I.P.L.T.Mihai Eminescu, mun.Balti")
print("-continui invatamantul in clasa a 10-a, profil real, a aceluiasi liceu")
print("APTITUDINI")
print("-abilitati comunicationale")
print("-adaptare rapida la conditiile de lucru")
print("-disponibila pentru a invata noi deprinderi profesionale")
print("LIMBI")
print("Limbi Materne: Romana,Rusa")
print("Limbi Straine: Germana-mediu(B1), Engleza-mediu(B1)")